on:
  workflow_run:
    workflows: [Lint and Test]
    branches: [main]
    types: 
      - completed


name: Release
defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          changelog-file: CHANGELOG.md
          allow-initial-development-versions: true
          prepend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}